export default {
  login: "sophiasagan",
id: 34404684,
node_id: "MDQ6VXNlcjM0NDA0Njg0",
avatar_url: "https://avatars1.githubusercontent.com/u/34404684?v=4",
gravatar_id: "",
url: "https://api.github.com/users/sophiasagan",
html_url: "https://github.com/sophiasagan",
followers_url: "https://api.github.com/users/sophiasagan/followers",
following_url: "https://api.github.com/users/sophiasagan/following{/other_user}",
gists_url: "https://api.github.com/users/sophiasagan/gists{/gist_id}",
starred_url: "https://api.github.com/users/sophiasagan/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/sophiasagan/subscriptions",
organizations_url: "https://api.github.com/users/sophiasagan/orgs",
repos_url: "https://api.github.com/users/sophiasagan/repos",
events_url: "https://api.github.com/users/sophiasagan/events{/privacy}",
received_events_url: "https://api.github.com/users/sophiasagan/received_events",
type: "User",
site_admin: false,
name: "Sophia Jung",
company: null,
blog: "",
location: "Michigan",
email: null,
hireable: null,
bio: " MS in Clinical Psychology | Current Computer Science and Web Development Student | Astronomy & Astrophysics Enthusiast ",
twitter_username: "KingSofieJ",
public_repos: 165,
public_gists: 1,
followers: 42,
following: 112,
created_at: "2017-12-09T20:51:51Z",
updated_at: "2020-11-19T03:17:54Z"
}
